version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  api-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=$NODE_ENV
    depends_on:
      - mongo
    volumes:
      - $PWD/node_api/logs:/home/node/logs